services:
  - type: web
    name: yearbook25-backend
    env: node
    plan: free
    region: singapore # Choose a region close to your users
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://students.iitgn.ac.in
      - key: CORS_ALLOW_ALL
        value: "true"
      - key: GOOGLE_DRIVE_FOLDER_ID
        fromGroup: google-drive
    healthCheckPath: /
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Origin, X-Requested-With, Content-Type, Accept, Authorization, X-CSRF-Token, X-Api-Version, Access-Control-Allow-Methods, Access-Control-Allow-Origin, Access-Control-Allow-Headers"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "86400"

# Environment variable groups for sensitive information
envVarGroups:
  - name: google-drive
    envVars:
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
        # Add your Google Drive folder ID in the Render dashboard
        # This keeps sensitive information out of your code repository
