services:
  - type: web
    name: yearbook25-backend
    env: node
    plan: free
    region: singapore # Choose a region close to your users
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    rootDir: .
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://students.iitgn.ac.in
      - key: CORS_ALLOW_ALL
        value: "true"
      - key: GOOGLE_DRIVE_FOLDER_ID
        fromGroup: google-drive
    healthCheckPath: /
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization, Origin"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "86400"

# Environment variable groups for sensitive information
envVarGroups:
  - name: google-drive
    envVars:
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
        # Add your Google Drive folder ID in the Render dashboard
        # This keeps sensitive information out of your code repository
